package com.nctech.hairxpertise.dtos;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) class representing information about a salon.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Salon {
    /**
     * The autogenerated unique identifier of the salon.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The name of the salon.
     */
    private String salonName;

    /**
     * The owner's name of the salon.
     */
    private String salonOwner;

    /**
     * The address of the salon.
     */
    private String salonAddress;

    /**
     * The contact information of the salon.
     */
    private String salonContact;

    /**
     * The number of employees working at the salon.
     */
    private Integer noOfEmp;

    /**
     * The type/category of the salon (e.g., beauty salon, hair salon).
     */
    private String salonType;

    /**
     * A description providing additional information about the salon.
     */
    private String salonDescription;
}
